
- task: DockerCompose@0
  inputs:
    containerregistrytype: 'Container Registry'
    dockerComposeFile: '**/docker-compose.yml'
    action: 'docker-compose up -d'

    frontend:
        build: ./nginx
        ports:
            - "80:80"
       
    mysql_db:
        container_name: mysql_db
        build: ./db
        environment:
            MYSQL_ROOT_PASSOWRD: 'd@t@b@s3'
        command:  --default-authentication-plugin=mysql_native_password
        volumes:
            - ./db:/docker-entrypoint-initdb.d
        ports:
            - '3306:3306'
        expose:
            - '3306'
  
    backend:
        container_name: backend_nodejs
        build: ./nodejs
        ports:
            - "8888:8888"
        links:
            - "mysql_db:mysql_db"
        depends_on:
            - mysql_db
        environment:
          DATABASE_HOST: mysql_db
        
              




